use_frameworks!

platform :ios, '13.0'

target 'BloctoSDK_Example' do
  pod 'BloctoSDK/Solana', :path => '../'
  pod 'BloctoSDK/Wallet', :path => '../'
  pod 'BloctoSDK/EVMBase', :path => '../'
  pod 'BloctoSDK/Flow', :path => '../'
  pod 'FCL', :path => '../../FCL'
  pod 'FlowSDK', :git => 'git@github.com:portto/flow-swift-sdk.git'
  pod 'Cadence', :git => 'git@github.com:portto/flow-swift-sdk.git'
  pod 'SnapKit'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'SolanaWeb3', :git => 'https://github.com/portto/solana-web3.swift.git'
  pod 'web3.swift', :git => 'https://github.com/portto/web3.swift.git', :branch => 'feat/adjust-dependency-version'
  pod 'EthereumSignTypedDataUtil'

  target 'BloctoSDK_Tests' do
    inherit! :search_paths

  end
end
