name: Testing
on:
  push:
    branches: 
    - main
  pull_request:
    types: 
    - opened
    - edited
    branches:
    - main
jobs:
  test:
    name: Testing Swift Package and iOS app
    runs-on: macOS-latest
    strategy:
        matrix:
          swift: ["5.0", "5.1", "5.2", "5.3", "5.4"]
          destination: ['platform=iOS Simulator,OS=15.2,name=iPhone 13 Pro']

    steps:
    - uses: actions/checkout@v1

    - name: Get swift version
      run: swift --version

    - name: start test
      run: echo start test!

    - name: clean build and test
      run: xcodebuild clean test -workspace ./Example/BloctoSDK.xcworkspace -scheme "BloctoSDK-Example" -destination "${destination}"
      env: 
         destination: ${{ matrix.destination }}