name: Testing
on:
  push:
    branches: 
    - main
  pull_request:
    types: [opened, reopened, edited, ready_for_review]
    branches:
    - main
jobs:
  test:
    name: Testing Swift Package and iOS app
    runs-on: macOS-latest
    strategy:
        matrix:
          swift: ["5.7"]
          destination: ['platform=iOS Simulator,OS=16.0,name=iPhone 14 Pro']

    steps:
    - uses: actions/checkout@v1
      with: 
        xcode-version: '14.1'

    - name: Install Dependencies
      run: |
        cd Example
        bundle install
        bundle exec pod install --repo-update
      shell: bash

    - name: Get swift version
      run: swift --version

    - name: Get xcode version
      run: xcodebuild -version

    - name: Get MacOS version
      run: sw_vers

    - name: start test
      run: echo start test!

    - name: clean build and test
      run: xcodebuild clean test -workspace ./Example/BloctoSDK.xcworkspace -scheme "BloctoSDK-Example" -destination "${destination}"
      env: 
         destination: ${{ matrix.destination }}
